# -*- coding: utf-8 -*-
"""Anubin Binoy_Python Class 1 _TN

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bkkOVgb6pAL73AXFAOhEuxm37Ct_4Bsz
"""

#Assignment 1- Create a two different examples for collective datatypes in python codes

#LISTS
#List with 3 integers

n=[1,2,3]
print(n)

#empty list
m=[]
#m is a list with mixed data types
m=[1,"Anubin Binoy",2.2]

#accessing list elements
print(m[1])

#engative indexing
print(m[-1])

#list slicing
print(m[0:2])

#adding elements to a list
m.append(55)
print(m)

#using extend
print("my list:",m)
m.extend(n)

print("after appending:",m)

#removing an item from the list
del m[2]
print(m)

#using remove
m.remove(55)

print(m)

#TUPLES
a=(0,[1,2,3],(4,5,6),8.2)
print(a)

print(type(a))

#indexing ans slicing
print(a[0])
print(a[-1])

print(a[2][1])

print(a[:3])
print(a[4:])

print(a[-3:])

#concatenation of tuples
b=(1,2)
c=(3,4)
print(b+c)

#using fucntions
def sum_and_avg(x,y,z):
  s=x+y+z
  a=s/3
  return(s,a)
(S,A)= sum_and_avg(3,8,5)
print('Sum=',S)
print('Avg=',A)

#SETS
#Finding the number of set elements
even_numbers = {2,4,6,8}
print('Set:',even_numbers)

# find number of elements
print('Total Elements:', len(even_numbers))

#set operations
#difference between two sets
# first set
A = {2, 3, 5}

# second set
B = {1, 2, 6}

# perform difference operation using &
print('Difference using &:', A - B)

# perform difference operation using difference()
print('Difference using difference():', A.difference(B))

#ASSIGNMENT 2

#creating a file
f = open("cFile.txt", "w")

#write in a file
f.write("Hello file")

f.write("This is the write command")
f.write("It allows us to write in a particular file")
f.close()

# Python code to illustrate append() mode
f = open("cFile.txt", "w+")
f.write("This will add this line")
f.close()

